
KEY_TIMEOUT = 'timeout'
KEY_METHOD = 'method'
KEY_OWNER = 'owner'
KEY_CUSTOMER = 'customer'
KEY_REFERENCE = 'reference'
KEY_PATH = 'path'
KEY_INTERFACE = 'interface'
KEY_VERSION = 'version'
KEY_ASYNC = 'async'
KEY_WITH_RETURN = 'withReturn'
KEY_CLASSPATH = 'classpath'
KEY_DUBBO_OWNER = 'owner'
KEY_DUBBO_CUSTOMER = 'customer'
KEY_HEARTBEAT = 'heartbeat'

DEFAULT_TIMEOUT = 1
DEFAULT_SERVICE_VERSION = '1.0.0'
DEFAULT_HEARTBEAT = 60
DEFAULT_FUTURE_CHECK_PERIOD = 0.03

DEFAULT_DUBBO_OWNER = 'Spartacus'
DEFAULT_DUBBO_CUSTOMER = 'consumer-of-sparta'

